admin:
  credentials:
    email: admin@beautysalon.com
    password: 1234

server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:file:./db/user_service_db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: user
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000

---
admin:
  credentials:
    email: admin@beautysalon.com
    password: 1234

spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
      prefer-ip-address: false
      hostname: ${spring.application.name}
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always